import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import RootLayout from "./components/Rootlayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>My App</title>
      </head>
      <body>
        <RootLayout>{children}</RootLayout>
      </body>
    </html>
  );
}

